import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Khu Du Lịch Tuyệt Tịnh Cốc Ninh Bình",
  description: "Khu Du Lịch Tuyệt Tịnh Cốc Ninh Bình",
  
  // 🟢 Thêm Open Graph để khi share link không còn "Generated by create next app"
  openGraph: {
    title: "Khu Du Lịch Tuyệt Tịnh Cốc Ninh Bình",
    description: "Khu Du Lịch Tuyệt Tịnh Cốc Ninh Bình",
    url: "https://tuyettinhcocninhbinh.com",
    siteName: "Tuyệt Tịnh Cốc Ninh Bình",
    locale: "vi_VN",
    type: "website",
    images: [
      {
        url: "https://tuyettinhcocninhbinh.com/og.jpg", // đổi bằng ảnh thật của bạn
        width: 1200,
        height: 630,
        alt: "Tuyệt Tịnh Cốc Ninh Bình",
      },
    ],
  },

  // 🟢 SEO bổ sung (giúp Google index đẹp hơn)
  robots: {
    index: true,
    follow: true,
  },

  // 🟢 Favicon
  icons: {
    icon: "/favicon.ico",
    apple: "/favicon.ico",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="vi">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
